export const FETCH_POSTS = 'FETCH_POSTS';
export const START_POSTS_FETCHING = 'START_POSTS_FETCHING';
export const STOP_POSTS_FETCHING = 'STOP_POSTS_FETCHING';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const SHOW_CONGRATULATION = 'SHOW_CONGRATULATION';
